# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

# Controls when the action will run. This action runs every 24 hours.
on:
  schedule:
    # every 12 hours
    - cron: "0 */24 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Generates a snake game from a GitHub user's contributions graph
      - uses: Platane/snk@v2
        with:
          github_user_name: KavishRAGHUBAR
          outputs: |
            dist/github-snake.svg?color_snake=red&color_dots=#263344,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/github-snake-dark.svg?color_snake=red&color_dots=#263344,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/ocean.gif?color_snake=red&color_dots=#263344,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Pushes the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
