name: Generate Snake

on:
  schedule:
    - cron: "0 */36 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: KavishRAGHUBAR
          outputs: |
            dist/github-snake.svg?color_snake=red&color_dots=#263344,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/github-snake-dark.svg?color_snake=red&color_dots=#263344,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/ocean.gif?color_snake=red&color_dots=#263344,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Optionally, add a step to show the status of the build for debugging.
      - run: git status

      # If you want to push changes, add a similar step.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
